#! /bin/sh

NED8=WRS_K8

SRCDIR=/common/home/bel/matthies/lnx/git/solveigh/qlib
#/common/home/bel/matthies/lnx/whiteRabbit/omnetpp-4.2/workspace/qlib
SIMDIR=/common/home/bel/matthies/lnx/whiteRabbit/

echo $SRCDIR
echo $SIMDIR

cd $SIMDIR/asl723/qlib/simulations

EDIR=../out/gcc-release/src
EXECUTABLE=qlib


chmod +x $EDIR/$EXECUTABLE
#echo $(pwd)
#echo $(ls $EDIR)

rm -rf *.csv *.tex

# run batch simulation
./$EDIR/$EXECUTABLE -f omnetppK8minHP.ini -u Cmdenv -c $NED8
mkdir K8HPmin
mv *.csv K8HPmin
mv *.tex K8HPmin
mv replaceInResults.sh K8HPmin


cd K8HPmin
chmod +x replaceInResults.sh 
./replaceInResults.sh