#! /bin/sh

NED3=WRS_K3

SRCDIR=/common/home/bel/matthies/lnx/git/solveigh/qlib
#common/home/bel/matthies/lnx/whiteRabbit/omnetpp-4.2/workspace/qlib
SIMDIR=/common/home/bel/matthies/lnx/whiteRabbit/

echo $SRCDIR
echo $SIMDIR

cd $SIMDIR/asl721/qlib/simulations

EDIR=../out/gcc-release/src
EXECUTABLE=qlib


chmod +x $EDIR/$EXECUTABLE
#echo $(pwd)
#echo $(ls $EDIR)

rm -rf *.csv *.tex

# run batch simulation
./$EDIR/$EXECUTABLE -f omnetppK3maxHP.ini -u Cmdenv -c $NED3
mkdir K3HPmax
mv *.csv K3HPmax
mv *.tex K3HPmax
mv replaceInResults.sh K3HPmax


cd K3HPmax
chmod +x replaceInResults.sh 
./replaceInResults.sh