#! /bin/sh

NED8=WRS_K8

#EDIR=../out/gcc-debug/src
EDIR=../out/gcc-release/src
EXECUTABLE=qlib


chmod +x $EDIR/$EXECUTABLE
#echo $(pwd)
#echo $(ls $EDIR)

rm -rf *.csv *.tex

./$EDIR/$EXECUTABLE -f omnetppK8maxHP.ini -u Cmdenv -c $NED8
mkdir K8HPmax
mv *.csv K8HPmax
mv *.tex K8HPmax
cp replaceInResults.sh K8HPmax

cd K8HPmax
chmod +x replaceInResults.sh 
./replaceInResults.sh