#! /bin/sh

NED8=WRS_K8

SRCDIR=/common/home/bel/matthies/lnx/git/solveigh/qlib
#common/home/bel/matthies/lnx/whiteRabbit/omnetpp-4.2/workspace/qlib
SIMDIR=/common/home/bel/matthies/lnx/whiteRabbit/

echo $SRCDIR
echo $SIMDIR

cd $SIMDIR/asl724/qlib/simulations

EDIR=../out/gcc-release/src
EXECUTABLE=qlib


chmod +x $EDIR/$EXECUTABLE
#echo $(pwd)
#echo $(ls $EDIR)

rm -rf *.csv *.tex

# run batch simulation
./$EDIR/$EXECUTABLE -f omnetppK8maxHP.ini -u Cmdenv -c $NED8
mkdir K8HPmax
mv *.csv K8HPmax
mv *.tex K8HPmax
mv replaceInResults.sh K8HPmax


cd K8HPmax
chmod +x replaceInResults.sh 
./replaceInResults.sh