#! /bin/sh

NED8=WRS_K8

#EDIR=../out/gcc-debug/src
EDIR=../out/gcc-release/src
EXECUTABLE=qlib


chmod +x $EDIR/$EXECUTABLE
#echo $(pwd)
#echo $(ls $EDIR)

rm -rf *.csv *.tex

./$EDIR/$EXECUTABLE -f omnetppK8minHP.ini -u Cmdenv -c $NED8
mkdir K8HPmin
mv *.csv K8HPmin
mv *.tex K8HPmin
cp replaceInResults.sh K8HPmin

cd K8HPmin
chmod +x replaceInResults.sh 
./replaceInResults.sh



