#! /bin/sh

NED3=WRS_N3

#EDIR=../out/gcc-debug/src
EDIR=../out/gcc-release/src
EXECUTABLE=qlib


chmod +x $EDIR/$EXECUTABLE
#echo $(pwd)
#echo $(ls $EDIR)

rm -rf *.csv *.tex

./$EDIR/$EXECUTABLE -f omnetppN3minHP.ini -u Cmdenv -c $NED3
mkdir N3HPmin
mv *.csv N3HPmin
mv *.tex N3HPmin