#! /bin/sh

NED3=WRS_K3

#EDIR=../out/gcc-debug/src
EDIR=../out/gcc-release/src
EXECUTABLE=qlib


chmod +x $EDIR/$EXECUTABLE
#echo $(pwd)
#echo $(ls $EDIR)

rm -rf *.csv *.tex

./$EDIR/$EXECUTABLE -f omnetppK3minHP.ini -u Cmdenv -c $NED3
mkdir K3HPmin
mv *.csv K3HPmin
mv *.tex K3HPmin
cp replaceInResults.sh K3HPmin

cd K3HPmin
chmod +x replaceInResults.sh 
./replaceInResults.sh