#! /bin/sh

NED3=WRS_N3

SRCDIR=/common/home/bel/matthies/lnx/git/solveigh/qlib
#common/home/bel/matthies/lnx/whiteRabbit/omnetpp-4.2/workspace/qlib
SIMDIR=/common/home/bel/matthies/lnx/whiteRabbit/

echo $SRCDIR
echo $SIMDIR

cd $SIMDIR/asl721/qlib/simulations

EDIR=../out/gcc-release/src
EXECUTABLE=qlib


chmod +x $EDIR/$EXECUTABLE
#echo $(pwd)
#echo $(ls $EDIR)

rm -rf *.csv *.tex

# run batch simulation
./$EDIR/$EXECUTABLE -f omnetppN3maxHP.ini -u Cmdenv -c $NED3
mkdir N3HPmax
mv *.csv N3HPmax
mv *.tex N3HPmax
mv replaceInResults.sh N3HPmax


cd N3HPmax
chmod +x replaceInResults.sh 
./replaceInResults.sh